const personalConstants = {
  SET_FIRST_USE_DATA: 'SET_FIRST_USE_DATA',
  SET_USER: 'SET_USER',
  SET_IS_LOGGED_IN: 'SET_IS_LOGGED_IN',
  SET_CURRENT_LANGUAGE: 'SET_CURRENT_LANGUAGE',
  SET_CURRENT_CURRENCY: 'SET_CURRENT_CURRENCY',
  SET_CURRENT_BOOK_ID: 'SET_CURRENT_BOOK_ID',
  SET_CURRENT_BOOK_DATA: 'SET_CURRENT_BOOK_DATA',
  RESET_PERSONALS_STATE: 'RESET_PERSONALS_STATE'
}

export default personalConstants
